version: ' 3.8'

services:
  php:
    build: './php_docker/'
    volumes:
      - ./www/:/var/www/html

  apache:
    build: './apache_docker'
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ./www/:/var/www/html

  mariadb:
    image: mariadb:11.2
    environment:
      - MYSQL_ROOT_PASSWORD=votre_mot_de_passe
    volumes:
      - blogdatabase:/var/lib/mysql