FROM php:8.2-fpm

#installation de dépendances pour l'activation des modules nécessaires
RUN apt-update && \ apt intall -y zip libzip-devlibpng-dev libicu-dev libxml2-dev 

# installation des modules

RUN docker-php-ext-install mysqli pdo do_mysqli gd zip intl xml

#nettoyage
RUN apt clean